config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  resources :accounts, only: [:show] do
    resources :parking_spots, only: [:new, :create]
    resources :bookings, only: [:index]
    member do
      get 'notifications', to: 'accounts#notifications'
    end
  end

  resources :parking_spots, only: [:show, :index] do
    member do
      patch 'available', to: 'parking_spots#toggle_available'
    end
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: [:destroy] do
    member do
      delete 'cancel', to: 'bookings#cancel_booking'
    end
  end

  resources :notifications, only:[:destroy]

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :parking_spot

  has_one :notification

  attr_accessor :duration

  validates :start_time, presence: true
  validates :date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    #TODO - GET ALL THE USER'S BOOKED PARKING SPOTS' BOOKINGS AND RETURN THEM IN AN ARRAY (@bookings)
    @bookings = []
    current_user.parking_spots.each do |spot|
      @bookings += policy_scope(Booking.where(parking_spot: spot)) unless spot.bookings.empty?
    end

    if @bookings.empty?
      @bookings = policy_scope(Booking.where(user: current_user.parking_spots.first))
    end
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.end_time = Time.zone.local_to_utc(params[:booking][:start_time].to_time) + params[:booking][:duration].to_i*3600
    @booking.user = current_user
    @booking.parking_spot = ParkingSpot.find(params[:parking_spot_id])
    @booking.total_price = params[:booking][:duration].to_i * @booking.parking_spot.price
    notification = Notification.create(account: @booking.parking_spot.user.account, notification_type: 'booking', sent_by: current_user.id, received_by: @booking.parking_spot.user.id)
    if @booking.save
      notification.update(booking_number: @booking.id)
      redirect_to account_path(current_user)
    else
      redirect_to parking_spot_path(@booking.parking_spot)
    end

    authorize @booking
  end


  def destroy
    ######################### WHEN A USER CANCELS HIS PARKING SPOT'S BOOKING(THE OWNER) ##############################################
    ######################### SENT_BY: THE PARKING SPOT OWNER'S ID, AND RECEIVED_BY: THE PERSON WHO BOOKED'S ID #########################

    @booking = Booking.find(params[:id])
    Notification.find_by(booking_number: @booking.id).destroy if Notification.find_by(booking_number: @booking.id)
    content = "#{current_user.full_name} has cancelled your reservation for #{@booking.parking_spot.title}"
    Notification.create(account: @booking.parking_spot.user.account, notification_type: 'cancelled_booking', content: content, sent_by: current_user.id, received_by: @booking.user.id)
    @booking.destroy

    redirect_to account_path(current_user)
    authorize @booking
  end

  def cancel_booking
    ######################### WHEN A USER CANCELS HIS UPCOMING BOOKING ################################################################
    ######################### SENT_BY: THE PERSON WHO BOOKED'S ID AND RECEIVED_BY: THE PARKING SPOT OWNER'S ID #########################
    @booking = Booking.find(params[:id])
    Notification.find_by(booking_number: @booking.id).destroy if Notification.find_by(booking_number: @booking.id)

    content = "#{current_user.full_name} has cancelled the reservation for #{@booking.parking_spot.title}"
    Notification.create(account: @booking.parking_spot.user.account, notification_type: 'cancelled_booking', content: content, sent_by: current_user.id, received_by: @booking.parking_spot.user.id)
    @booking.destroy

    redirect_to account_path(current_user)
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :duration, :date)
  end
end

app/views/bookings/index.html.erb
<div class="container mt-5">
  <h2 class='text-center pt-2'>Your booked spots</h2>
  <% unless @bookings.empty? %>
    <% @bookings.each do |booking| %>
      <div class="card-parking-spot mb-3">
        <%= cl_image_tag booking.parking_spot.photo, height: 300, width: 400, crop: :fill %>
        <div class="card-parking-spot-infos align-items-center flex-grower text-center">
          <h2 class="text-center mb-2"><%= booking.parking_spot.title %></h2>
          <p class="mb-2"><strong><%= booking.date.strftime('%e %B') %></strong>, <%= booking.start_time.strftime('%T').chomp(':00') %></strong> - <strong><%= booking.end_time.strftime('%T').chomp(':00') %></p>
          <div class="d-flex">
            <button type="button" class="btn btn-primary btn-block mt-auto mb-2 ml-1" data-toggle="modal" data-target="#bookParkingSpot">
              View
            </button>
            <button id="cancel-booking" class="btn btn-danger btn-block mt-0 mb-2 ml-1">Cancel</button>
            <%= link_to 'Cancel', booking_path(booking), id: 'delete-booking-btn', style: 'display: none;', method: :delete %>
          </div>
          <div class="modal fade" id="bookParkingSpot" tabindex="-1" role="dialog" aria-labelledby="bookParkingSpotTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalCenterTitle"><%= booking.parking_spot.title %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="d-flex align-items-center">
                      <%= link_to account_path(booking.user)  do%>
                      <%= cl_image_tag booking.user.photo, id: "avatar-manage-bookings-popup", class: 'mr-3' %>
                      <% end %>
                      <div class="d-flex align-items-end">
                        <div>
                          <h2><%= booking.user.full_name %> has booked your spot!</h2>
                          <p>Booking is on <strong><%= booking.date.strftime('%e %B') %></strong></p>
                          <p>From <strong><%= booking.start_time.strftime('%T').chomp(':00') %></strong> to <strong><%= booking.end_time.strftime('%T').chomp(':00') %></strong></p>
                        </div>
                        <h5>$<%= booking.total_price %></h5>
                      </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    <% end %>
  <% else %>
    <h5 class="text-center mt-5"><em>You have no booked spots.</em></h5>
  <% end %>
</div>