config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  resources :accounts, only: [:show] do
    resources :parking_spots, only: [:new, :create]
    resources :bookings, only: [:index]
    member do
      get 'notifications', to: 'accounts#notifications'
    end
  end

  resources :parking_spots, only: [:show, :index] do
    member do
      patch 'available', to: 'parking_spots#toggle_available'
    end
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: [:destroy] do
    member do
      delete 'cancel', to: 'bookings#cancel_booking'
    end
  end

  resources :notifications, only:[:destroy]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<i class="fas fa-bars color-white" id="open-nav-btn"></i>
<div id="mySidenav" class="sidenav">
  <% if current_user %>
    <ul>
      <li>
        <div class="nav-top pb-3">
          <div class="d-flex justify-content-between mb-3">
            <span></span>
            <h3 id="close-nav-btn" class="m-3"><i class="fas fa-arrow-left color-white"></i></h3>
          </div>
          <div class="p-3">
            <%= link_to account_path(current_user), class: "d-flex align-items-center justify-content-between mouse-hover" do%>
              <%= cl_image_tag current_user.photo, alt: "user avatar", class: "avatar-large" %>
              <h4 class="mb-0"><%= current_user.full_name %></h4>
            <% end %>
          </div>
        </div>
      </li>
      <li class="p-3 border-top">
        <%= link_to notifications_account_path(current_user.account), class: "navbar-img align-items-center justify-content-between d-flex" do %>
          <%= image_tag "notification.png" %>
          <% if Notification.where(received_by: current_user.id, seen: false).count > 0 %>
            <h5 class="mb-0">Notifications (<strong><%= Notification.where(received_by: current_user.id, seen: false).count %></strong>)</h5>
          <% else %>
            <h5 class="mb-0">Notifications (<%= Notification.where(received_by: current_user.id, seen: false).count %>)</h5>
          <% end %>
        <% end %>
      </li>
      <li class="p-3 border-top">
        <%= link_to "/", class: "navbar-img align-items-center justify-content-between d-flex" do %>
          <%= image_tag "parking.png" %>
          <h5 class="mb-0">Find Parking</h5>
        <% end %>
      </li>
      <li class="p-3 border-top">
        <%= link_to new_account_parking_spot_path(current_user.account.id), class: "navbar-img align-items-center justify-content-between d-flex mouse-hover" do%>
          <%= image_tag "plus.png"%>
          <h5 class="mb-0">Add a new spot</h5>
        <% end %>
      </li>
      <li class="p-3 border-top">
        <%= link_to account_bookings_path(current_user.account.id), class: "navbar-img align-items-center justify-content-between d-flex mouse-hover" do%>
          <%= image_tag "https://www.svgrepo.com/show/70453/car-transport.svg"%>
          <h5 class="mb-0">Manage Spots</h5>
        <% end %>
      </li>
      <li class="p-3 border-top">
        <%= link_to destroy_user_session_path, class: "navbar-img align-items-center justify-content-between d-flex mouse-hover", method: :delete do%>
          <%= image_tag "logout.png"%>
          <h5 class="mb-0">Log out</h5>
        <% end %>
      </li>
    </ul>
  <% else %>
    <ul>
      <li>
        <div class="nav-top pb-3">
          <div class="d-flex justify-content-between mb-3">
            <span></span>
            <h3 id="close-nav-btn" class="m-3"><i class="fas fa-arrow-left"></i></h3>
          </div>
          <div class="p-3">
            <%= link_to new_user_session_path, class: "d-flex align-items-center justify-content-between navbar-img mouse-hover" do%>
                <%= image_tag "avatar.png"%>
              <h4>Log In</h4>
            <% end %>
          </div>
        </div>
      </li>
     <li class="p-3 border-top">
       <%= link_to "/", class: "navbar-img align-items-center justify-content-between d-flex" do %>
         <%= image_tag "parking.png" %>
         <h5 class="mb-0">Find Parking</h5>
       <% end %>
     </li>
    </ul>
  <% end %>
</div>